# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sporeCount24', models.CharField(max_length=10)),
                ('sporeCount48', models.CharField(max_length=10)),
                ('sporeCount72', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleType', models.CharField(choices=[('a', 'air'), ('s', 'swab'), ('w', 'wipe'), ('o', 'other'), ('pc', 'positive-control'), ('mc', 'media-control')], max_length=2)),
                ('zoneID', models.CharField(max_length=100)),
                ('subCategory', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('serialNumber', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='sampleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assayName', models.CharField(max_length=100)),
                ('coge', models.CharField(max_length=100)),
                ('samplers', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('environment', models.CharField(max_length=100)),
                ('spacecraft', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='samplingEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling_event.sampleEvent'),
        ),
        migrations.AddField(
            model_name='plate',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling_event.sample'),
        ),
    ]
