# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling_event', '0002_sample_accountable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleevent',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
